[tool.poetry]
name = "adumo"
version = "0.1.10"
description = ""
authors = ["Wayne <wayne@flickswitch.co.za>"]

[tool.poetry.dependencies]
python = "^3.9"
httpx = "^0.21.3"
environs = "^9.4.0"
flake8 = "^4.0.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
black = "^21.12b0"
pytest-vcr = "^1.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
