[build-system]
requires = [
    "Babel==2.9.1",
    "certifi==2021.5.30",
    "charset-normalizer==2.0.4",
    "dnspython==2.1.0",
    "docutils==0.17.1",
    "packaging==21.0",
    "Pygments==2.10.0",
    "pymongo==3.12.0",
    "pyparsing==2.4.7",
    "python-dotenv==0.19.0",
    "requests==2.26.0",
    "urllib3==1.26.6",
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"