[tool.poetry]
name = "file-storage"
version = "0.2.4"
description = "Universal tool for file storages"
authors = ["Moleque <molecada@yandex.ru>"]
license = "GPL-3.0 License"

[tool.poetry.dependencies]
python = "^3.6"
boto3 = "^1.17.66"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
