[tool.poetry]
name = "ons_utils"
version = "0.1.2-alpha.0"
description = "A suite of pyspark, pandas and general pipeline utils for ONS projects."
authors = ["Mitchell Edmunds <Mitchell.Edmunds@ext.ons.gov.uk>"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.6.8"
pyspark = "2.4.1"
pandas = "1.1.5"
pyyaml = "^6.0"
flatten-dict = "^0.4.2"
pytest = "^6.2.5"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
chispa = "^0.8.2"
pytest-lazy-fixture = "^0.6.3"
coverage = "^6.2"

# [[tool.poetry.source]]
# name = "art-p-01"
# url = "http://art-p-01/artifactory/api/pypi/yr-python/simple/"
# default = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
