[tool.poetry]
name = "byu-gradescope-harness"
version = "0.1.3"
description = "A test harness for Gradescope autograding"
authors = ["Gordon Bean <gbean@cs.byu.edu>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

