[tool.poetry]
name = "fact-lake"
version = "0.0.3"
description = "A datalake that is keeping up to date with your factcast"
authors = ["Eduard Thamm <eduard.thamm@thammit.at>"]
license = "Apache-2.0"
readme = "README.md"
documentation = "https://fact-lake.readthedocs.io/en/stable/"
repository = "https://gitlab.com/friendly-facts/fact-lake"
keywords = ["event-sourcing","validation"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Database",
    "Topic :: Software Development :: Libraries",
    "Typing :: Typed"
]

[tool.poetry.dependencies]
python = "^3.8"
sphinx = {version = "<4", optional = true}
sphinx-click = {version = "^2.7", optional = true}
sphinx-rtd-theme = {version = "^0.5", optional = true}
sphinx-autodoc-typehints = {version = "^1.12", optional = true}
pymongo = "^4.0.1"
pyfactcast = "^0.0.9"
cryptoshred = "^0.0.7"
pydantic = "^1.9.0"
rich = "<11"
typer = "<0.4"

[tool.poetry.extras]
docs = ["sphinx","sphinx-click","sphinx-rtd-theme","sphinx-autodoc-typehints"]

[tool.poetry.dev-dependencies]
Sphinx = "<4"
black = "^21.5b1"
flake8 = "^3.9"
flake8-bugbear = "^21.4"
pytest = "^6.2"
mypy = "^0"
rstcheck = "^3.3"
sphinx-autobuild = "^2021.3"
pytest-cov = "^2.11"
pytest-randomly = "^3.8"
pre-commit = "^2.12"
pytest-mock = "^3.6"
flake8-annotations = "^2.6"
safety = "^1.10"
flake8-docstrings = "^1.6"
nox = "^2021.6.6"
docker-compose = "^1.29.2"
testcontainers = "^3.4.2"

[tool.poetry.scripts]
fact-lake = 'fact_lake.cli:typer_app'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = ["*__init__.py"]

[tool.pytest.ini_options]
addopts = "-rsxX -l --tb=short --strict-markers --cov-report term --cov=fact_lake --cov-branch"
# TODO: --cov-fail-under=85
xfail_strict = true
testpaths = [
    "tests",
]
filterwarnings = "ignore:.*the imp module is deprecated.*:DeprecationWarning"
markers = [
  "integration: marks tests that use mock and are therefore slower.",
  "usecase: marks tests that represent business logic.",
  "containers: marks tests that will spin up test containers."
]

[tool.black]
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.nox
    | _build
    | buck-out
    | build
    | dist
  )/
  | .cache
  | .venv
)
'''
